spring.application.name=SpringSecurity

## Connection string and user details
spring.datasource.url = jdbc:mysql://localhost:3306/security?CreateDatabaseIfNotFound=true
spring.datasource.username = root
spring.datasource.password = Msizi@11

##hibernate property
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

## Database management
spring.jpa.generate-ddl=true
spring.jpa.hibernate.dll-auto = update
spring.jpa.show-sql =  true
